name: Matchstick unit tests

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install commands
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          registry-url: https://registry.npmjs.org
      - name: yarn add ts-node
        run: yarn add ts-node
      - name: yarn
        run: yarn
      # Run tests
      - name: Run Graph unit tests
        run: yarn test
